baseURL = '//manavjain.sh/'
languageCode = 'en-us'
title = 'Manav Jain'
theme = 'nightfall'

[menu]
  [[menu.header]]
    name = "posts"
    weight = 1
    url = "posts"
  [[menu.header]]
    name = "notes"
    weight = 1
    url = "/notes"

[params]
  author = "Manav Jain"
  user = "user"
  hostname = "manavjain.sh"

  readingTime = true  # Show reading time on post page
  published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/manavbjain"

[[params.social]]
key = 1
name = "linkedin"
url = "https://www.linkedin.com/in/manavbjain/"

[[params.social]]
key = 2
name = "email"
url = "mailto:manav_j[at]outlook[dot]com" 


